### PR TITLE
Ch setup api documentation

### PR DESCRIPTION
**Pull request by iphyokafor**

### CODE REVIEW

**Review by thatkazuk1 — APPROVED** [review]
Next time, resolve all merge conflicts before raising a pull request

**Comment by thatkazuk1** [comment]
[Setup API documentation using swagger](https://trello.com/c/am9kR2e3/8-setup-api-documentation-using-swagger)

**Comment by thatkazuk1** [comment]
[Setup API documentation using swagger](https://trello.com/c/am9kR2e3/8-setup-api-documentation-using-swagger)

**Comment by iphyokafor** [comment]
Okay, thanks.

**Pull request merged**
